# Generated by Django 3.2.5 on 2021-07-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-created',)},
        ),
    ]
